### ISSUE TITLE
Hello, i wanted to finish the setup of my project, but after selecting the prior knowledge and pressing "finish", the program told me that there was a memory error. How can I fix this? Thank you for your help! 

### ISSUE THREAD

**Issue by Metaanalyse** [asreview/asreview#1003]
**Describe the bug**
*What happened? And what did you expect to happen?*

**To Reproduce**
Steps to reproduce the problem:

**Screenshots**

**Version information**
 - OS: [e.g. Windows]
 - ASReview version [e.g. 0.6.2]

**Additional context**

**Comment by Rensvandeschoot** [comment]
Dear @Metaanalyse, thank you for reporting the issue!

Could you maybe provide some additional information so that we can help you to solve the issue? 

We provided some questions in the template that might guide you. In your case, you might want to add information about your dataset size (number of records and size of the file), which feature extractor you have chosen, and the exact warning message you received. Also, could you maybe put your question in the message and use a clear and concise title for your issue? Thanks!

**Comment by Rensvandeschoot** [comment]
We have not yet heard back from @Metaanalyse, as soon as more information is provided we will re-open the issue.
