### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#1064]
### Discussed in https://github.com/asreview/asreview/discussions/1063

<div type='discussions-op-text'>

<sup>Originally posted by **juliandwain** May  5, 2022</sup>
Hi,
thanks for this amazing library!

**Describe the bug**
I created a dataset by myself from a Scopus search and transformed it so that it can be interpreted by ASReview.
The dataset can be uploaded without any issues.
I know this is not an issue of ASReview itself, I assume that the issue is within the dataset, but I am not able to figure out why the overflow error appears.

**To Reproduce**
Upload the dataset and follow the instructions. The dataset is added as attachment.

**Screenshots**
![image](https://user-images.githubusercontent.com/38472982/166891141-286780b4-4cbe-421d-9d63-820b99485c75.png)
![image](https://user-images.githubusercontent.com/38472982/166890566-66385a8e-cb41-406d-a6cb-4ea3fd8c632f.png)

**Version information**
 - OS: Windows
 - ASReview version 0.19.1

**Additional context**
[220505_Scopus_data.csv](https://github.com/asreview/asreview/files/8629829/220505_Scopus_data.csv)

</div>

**Comment by J535D165** [comment]
@juliandwain I can't reproduce this issue in version 0.19 on macOS. 

The issue might be an integer overflow on Windows systems caused by the `record_id` column. You can rename or delete this column such that ASReview ignores it (record_ids are used by ASReview internally, but are generated on the fly if not present). 

This dataset is also "fully labeled". This means that there are labels identified by ASReview. This is the result of the `label` column. If this is intentional, there is nothing to screen. If this wasn't intentional, then renaming this column is also advised.

**Comment by PeterLombaers** [comment]
Apparently this does not happen on mac because the python basic int type is 64 bit long: https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma
Renaming the 'record_id' column should fix it though, as should (#1066).

**Comment by juliandwain** [comment]
I am able to resolve the issue when changing the 'record_id' column from the EID of the articles to a simple index numbering (i.e., 0,1,2,....).
Nevertheless, I do not understand why there is an overflow since the EID number is not an integer that cannot be handled by the OS.

Anyway, thank you all for your help! I really appreciate it!

**Comment by J535D165** [comment]
Closed via #1066. 

Released v0.19.2 with this fix. https://github.com/asreview/asreview/releases/tag/v0.19.2 

Thanks @juliandwain and @PeterLombaers.
