### ISSUE TITLE
Prior knowledge is not detected in exploration & simulation modes

### ISSUE THREAD

**Issue by jpeacock29** [asreview/asreview#1236]
**Describe the bug**
When using exploration & simulation modes, prior knowledge is not detected in the data set.

**To Reproduce**
1. Create a new project. Give it a title and set it to Exploration or Simulation mode.
2. Select Data from a Benchmark Dataset or upload your own labelled data set and click Save.
3. ASReview still prompts the user to "Add prior knowledge" rather than detecting the existing prior knowledge.

Thank you and apologies if this is a misunderstanding of how the software is supposed to work!

**Version information**
 - OS: OSX 11.6.4
 - ASReview version: 1.0

**Comment by gimoAI** [comment]
Hi @jpeacock29,

This is how `Exploration` & `Simulation `mode are supposed to work! Both modes **do** detect existing prior knowledge in the dataset, when you click on "add prior knowledge" you will find that you can manually add prior knowledge and that the prior given labels are shown. This is in contrast with `Oracle` mode where all prior knowledge is added automatically. This has to do with the purpose of `Exploration `& `Simulation `mode:
- **`Exploration`** is useful for teaching purposes because, while labeling, a blue bar is displayed on top of the record indicating whether the record has been labeled relevant or irrelevant in the dataset. If all prior knowledge would be detected and used automatically, then there would be nothing left to label and thus nothing left to "explore".
- **`Simulation`** is used to simulate the process of reviewing records with ASReview. If all labels were recognized as prior knowledge, there would be nothing left of the reviewing process to simulate. In a real simulation you would probably want to select a few articles that you know to be relevant and irrelevant as a starting point, that is why you have to use "Add prior knowledge" to add some prior knowledge manually.

Does this answer your question?

Kind regards,
Gijs

**Comment by jpeacock29** [comment]
Got it, thank you so much for taking the time to explain! I'll have to revisit the docs and figure out how I missed this :)
