### ISSUE TITLE
doc2vec not available - even though gensim is installed

### ISSUE THREAD

**Issue by LukasWallrich** [asreview/asreview#1310]
Probably this just shows my lack of understanding of python - but I can't get doc2vec to work. Based on the documentation, I have installed gensim (both locally and globally) and when I open python3 in the folder where asreview lives, I can import gensim without trouble. However, in asreview, the option continues to be greyed out.

If this is just a usage issue, should it be documented more clearly?

**Comment by LukasWallrich** [comment]
Note that I have also tried installing gensim in a virtual environment as per #426 - still no doc2vec ...

**Comment by PeterLombaers** [comment]
Hi Lukas!
The reason that the doc2vec feature extraction is greyed out is that it doesn't work in combination with Naive Bayes. The [implementation of Naive Bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html) that we use does not accept negative feature values. So any feature extraction method that produces negative values will not work in combination with it. There might be other solutions like changing the feature vectors, but right now ASReview just does not allow the combination. If you select Logistic Regression as a classifier instead of Naive Bayes, the option to select doc2vec will become available again.

I agree that this definitely could be documented more clearly. Maybe a table in the documentation showing which combinations (classifier + feature extraction) are allowed. Or in the screen where you select the model there could be an explanation why certain options are greyed out.

**Comment by Rensvandeschoot** [comment]
Feel free to start a PR with suggestions how to improve the documentation! It might fit in the [section on selecting a model](https://asreview.readthedocs.io/en/latest/project_create.html#model). For the underlying file, go to: https://github.com/asreview/asreview/blob/master/docs/source/project_create.rst
