### ISSUE TITLE
Connect to other (non-SQLite) databases?

### ISSUE THREAD

**Issue by jbiggsets** [asreview/asreview#1421]
## Feature Request

**Describe the solution you'd like**
I was wondering if there's a way to connect ASReview to a database other than SQLite.

**Comment by J535D165** [comment]
Currently, this is not possible (out of the box). Can you share some details of your use case so we can consider a potential implementation?

**Comment by J535D165** [comment]
Thanks! 

ASReview uses 1 SQLite database per project (see the `~/.asreview` folder). Back then, there was an idea to store all data in one central database. However, this had also some serious drawbacks. Due to the current structure, replacing the SQLite databases with one central SQLite database or another DB is hard. For now, S3 might be the most pragmatic solution (wondering how you will do this btw).

**Comment by abelsiqueira** [comment]
@jbiggsets, are you planning to run simulations or use the web interface?

**Comment by abelsiqueira** [comment]
Thanks for the answer. I'm working on running simulations in the cloud, so I was wondering if there was some intersection.
I don't know much about AWS ECS, so I was also curious about why you are using it instead of directly using an EC2 instance. Are you hosting ASReview for a larger group of people?
And let me know if the Docker image attends to your needs.
