### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Lieven123** [asreview/asreview#1469]
asreview keeps tellen: "failed to connect to server. Please restart the software"
Restarting is not the solution. 
I'm connecting to the server, other programms do work. 
 
![WhatsApp Image 2023-06-09 at 16 02 58](https://github.com/asreview/asreview/assets/136227338/af2a621a-2beb-48fe-9b65-4f40fe69ab5a)

**Comment by Rensvandeschoot** [comment]
Thank you for reporting this issue. In order to assist you further, it would be helpful if you could provide the output from the Command Line Interface (CLI) when you encounter this error. This will give us more insight into the underlying problem.

To do this, simply copy the text that appears in the command line and paste it here in your response.

This information will help us diagnose the issue more effectively. We appreciate your patience and cooperation.

**Comment by Rensvandeschoot** [comment]
This issue has been inactive for a while. If you're still encountering the problem, please feel free to reopen it and provide any additional details that might help us resolve it. Otherwise, to help keep our issue tracker manageable, I'll be closing this for now. Thank you for your understanding and support.
