### ISSUE TITLE
Class BaseReview has no method _write_to_state

### ISSUE THREAD

**Issue by jf29medma** [asreview/asreview#1526]
Hello everybody,

I am currently using the API and try to run a review. When I execute the method 'review()' I get following error:
![Screenshot 2023-09-12 191325](https://github.com/asreview/asreview/assets/142770314/e97092c3-21ec-46ca-82a3-495086b357fe)

After looking into the documentation I saw that there is no method '_write_to_state()' for the class 'BaseReview'. Maybe there was one but I could not find any 🤔

**Comment by J535D165** [comment]
It is interesting to see you are interacting with the ASReview library this deeply! Can you share more of your code? Ideally a reproducible example.

**Comment by PeterLombaers** [comment]
Thanks for reporting this bug! The problem is [here](https://github.com/asreview/asreview/blob/0bbf7a240048e55b1848cdc15af9cdc5f28c02f6/asreview/review/base.py#L197), where  `BaseReview` uses a method that only exists in the child class `ReviewSimulate`. For the simulation mode, `ReviewSimulate` keeps the data in memory instead of writing it away to the state file. When the method `ReviewSimulate_write_to_state` is called, the data in memory is written away. So when using `ReviewSimulate`, at the end of the review the final data should be written away. For some reason this ended up in `BaseReview` and not `ReviewSimulate`. I'll make a pull request with a quick fix.

The deeper problem is that these `Review` classes are a bit of a mess. They set up certain things which would ideally be set up in the `ASReviewProject` class. And then we don't actually use the `BaseReview.review` ever. We only use `ReviewSimulate.review` for the simulation mode and `BaseReview.train` for training new models. So these are prime candidates for a refactor. That would make them better usable via the python api.
