### ISSUE TITLE
Option to see when a project started or was opened for the last time

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#368]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Users want to see when a project was opened for the last time and when the project was started 

**Describe the solution you'd like**
An option to view when I opened a project for the last time and when I started a project. This could be shown in the project dashboard or at overview of the projects

**Why would you like to have this feature**
For example this shows how old the used dataset is and in in which version of ASReview the project started and was opened for the last time

**Comment by Rensvandeschoot** [comment]
@PeterLombaers Is this related to the work you are doing with our statefile?

**Comment by PeterLombaers** [comment]
I'd think the time when an abstract was labeled should be part of the statefile. Then you can always calculate the time to each decision, in particular the first decision and the last decision. 

In theory you could open a project, maybe look at the statistics, but not label any abstract. I don't think that should be part of the state file, since it has nothing to do with the machine learning part.

**Comment by Rensvandeschoot** [comment]
I agree with both. Is this logged already in the statefile?

**Comment by PeterLombaers** [comment]
Yes, its already in there! Not sure if there already is an easy method to get it out, but that shouldn't be difficult to implement (at least in the backend. The frontend I know nothing about :)
