### ISSUE TITLE
Possibility to see the names of the author

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#376]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Some people that have used ASReview would like to have an option in the settings so they can see the names of the authors of the article. They think the current amount of information is very small.

**Describe the solution you'd like**
A setting to show the names of the authors during the screening proces under the title. Respondents didn't say anything about if the names should also be taken into account when training the model, it's good to think about if this should be taken into account when training the model.

**Comment by Rensvandeschoot** [comment]
Thanks for reporting this feature. Many people ask us about showing authors or other information. We believe this will induce bias in the decision making. @bmkramer would you mind explaining why? :-)

**Comment by bmkramer** [comment]
As @Rensvandeschoot indicated, we believe decisions to include/exclude papers should be made based solely on the content of the paper (relevance and methodological quality), and not be influenced by proxies like journal reputation or author names. 

If a publication would otherwise not be included based on content, should it be included because it's from a particular research group, or because it's published in a certain journal? And vice versa, should name recognition or journal brand influence inclusion of a paper that is in itself seems relevant and methodologically sound? 

Of course, when clicking through to the paper from ASReview, users will still be able to check the names of the authors and the publication venue. We do not prevent that, but since we want to avoid bias in screening as much as possible, we do not show this information in ASReview itself.
