### ISSUE TITLE
Option to add comments to you decisions

### ISSUE THREAD

**Issue by SagevdBrand** [asreview/asreview#377]
## Feature Request

Some users want to label irrelevant publications because they might be interesting for the theoretical framework for example.
Other users would like to make a note on why they marked a publication as relevant or irrelevant.

A solution might be to add notes to each decision. This could result in an extra column in the export file called 'comments' for example?

**Comment by J535D165** [comment]
This is a good feature to add!

Something to think about in #334. After this PR is merged, we can implement such a thing in the frontend.

**Comment by MartijnUX** [comment]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/45943709/110351448-20fcea00-8035-11eb-9bd9-064ff29745f9.png">

**Comment by MartijnUX** [comment]
For the first round we would like to give the user the possibility to add notes to an article. As an user I want to add notes, so that I can read in the report what my notes were. 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/45943709/110351709-63262b80-8035-11eb-8f5d-0c4a2d76a67d.png">

**Comment by J535D165** [comment]
Thanks! Do you have suggestions for expanding and collapsing this panel?

**Comment by MartijnUX** [comment]
I suggest, that the "notes" feature is always on the screen. If we have the function in the next upgrade, I will take this function to test with real users.

**Comment by MartijnUX** [comment]
Empty state
<img width="569" alt="image" src="https://user-images.githubusercontent.com/45943709/111468321-b4b17300-8725-11eb-8351-70b67bd56623.png">
Filling state
<img width="569" alt="image" src="https://user-images.githubusercontent.com/45943709/111468355-bda24480-8725-11eb-9d3c-5d502a0d5c90.png">
Filled and added state
<img width="566" alt="image" src="https://user-images.githubusercontent.com/45943709/111469649-3950c100-8727-11eb-823f-e80bbab450fa.png">

@terrymyc @J535D165 From UX Research, we know users wants to add notes, to an article while reviewing. We could start by adding a comment box above the Screening options, and under the article.

Front-end question: Is it possible to auto-save while typing or does that influence the CPU to much? Otherwise a button is good enough for ASReview (user test question)

**Comment by MartijnUX** [comment]
> Thanks! Do you have suggestions for expanding and collapsing this panel?

I suggest, that the "notes" feature is always on the screen. If we have the function in the next upgrade, I will take this function to test with real users.

**Comment by terrymyc** [comment]
> Front-end question: Is it possible to auto-save while typing or does that influence the CPU to much? Otherwise a button is good enough for ASReview (user test question)

Autosave could be possible, but how can we notify a user the notes are saved? Maybe a button could be an indicator. Like the buttons for filling state & filled and added state. Either press enter or click the button to save the notes after filling.
