### ISSUE TITLE
no h5 anymore

### ISSUE THREAD

**Issue by paprika27** [asreview/asreview#464]
**Describe the bug**
Trying to follow the visualization rtd does not work: the system cannot find the specified path
These days, there is a result.json inside an exported .asreview - this has to be retrieved from the archive for asreview plot it. This should be updated in the docs.

**To Reproduce**
Steps to reproduce the problem:
follow the visualization basic usage example

**Screenshots**
n.a.

**Version information**
 - OS: windows
 - ASReview version .15

**Additional context**

**Comment by Rensvandeschoot** [comment]
Dear @paprika27, thank you for reporting this! We'll get to it asap.

**Comment by J535D165** [comment]
Thanks you for your report @paprika27. You are referring to the [asreview-visualization documentation](https://asreview.readthedocs.io/en/latest/plugins/plugin_visualization.html). Indeed, that page makes use of `.h5` files, which are the output of the [simulation functionality of ASReview](https://asreview.readthedocs.io/en/latest/guides/sim_overview.html) (which supports JSON and HDF5 files). 

Since version 0.15, you can plot the output of ASReview (`.asreview`) project files as well. Use the following code: 
```
asreview plot ptsd-bug-464.asreview 
```

Are you interested in making a Pull Request with clarified documentation? Please let me know if you need any help.

**Comment by paprika27** [comment]
Thanks! Being able to read .asreview is missing from the cmd error

     ValueError: Expected ASReview file or file .\XXX with extension ['.h5', '.hdf5', '.he5', '.json'].

I think adding your answer to the doc would be gold, I'll see if I can figure out how to use github..
