### ISSUE TITLE
Post-Screening: Downloading Excel-file does not work anymore?

### ISSUE THREAD

**Issue by AnoukTicheloven** [asreview/asreview#507]
I am conducting a review in ASReview and I do not manage to download the results as an excel-File (CSV-file does work).

Before, I had no problems with downloading an excel-file from ASreview, 
I thought it might have been because of the big dataset (14.649 articles), but earlier on in the process I downloaded an excel-File already and then it worked. I also waited to see if it just needed time (this was not the case). I also closed ASreview and restarted the computer, did not work either. Another explanation might be that I used the review history button and I changed some classifications because of a reliability analysis I conducted with a colleage (I included articles I first excluded and the other way around). I do not think that is the reason though?

I use Windows and ASreview 0.16.

![Bild_2021-03-12_142900](https://user-images.githubusercontent.com/80527558/110946544-48a6c780-833f-11eb-9ef4-2e521b329372.png)

Hope you can help out!

**Comment by Rensvandeschoot** [comment]
Dear @AnoukTicheloven, thank you for reporting this issue to us. Luckily you were able to save the `.csv` file which you can also import in Excel if you would like. But, the excel export should work, so let's do some debugging:

Could you first try to [remove the temorary files](https://asreview.readthedocs.io/en/latest/intro/installation.html#remove-temporary-files). Can you then import your exported `.csv` file into a new project. And can you then try to export an excel file? Please wait for at least 10 minutes since you have a large database (it shoulnd't take this long, but just to be sure). If it still does not work, can you then copy-paste all lines in the CMD as a code block in a reply? 

So, all the text in this CMD:

![](https://asreview.readthedocs.io/en/latest/_images/v0.14_00_cmd.png)

And,

```
This is a code block
```


Thanks!

**Comment by AnoukTicheloven** [comment]
Thank you, after removing the temporary files it worked!

**Comment by Rensvandeschoot** [comment]
Thanks for letting us know!
