### ISSUE TITLE
Problem in Project Importing

### ISSUE THREAD

**Issue by Vaibhav-DTx** [asreview/asreview#515]
**Describe the bug**
I have saved two projects. I tried to import one of the projects from the Home screen. While attempting to do this, importing a saved project took forever. Finally, I closed the window and also the command prompt window. I then started a new command prompt window, and launched "asreview lab" again. Now, there were three projects, the first two, as well as a copy of the project I tried to import, with the name with suffix "_copy".

*What happened? And what did you expect to happen?*

I expected to import the project normally, without error, and without creating a copy. 

**To Reproduce**
Steps to reproduce the problem:
While trying to reproduce it, I could not reproduce the problem. 

**Screenshots**

**Version information**
 - OS: Windows 10
 - ASReview version 0.16

**Additional context**
Probably, it was due to the fact that I had interrupted a review cycle, and wanted to quit labelling the records. While trying to import the project, after selecting the file, the dialogue box with "import" button never disappeared.

**Comment by terrymyc** [comment]
Hi @Vaibhav-DTx, thanks for reporting this issue! It looks like an accident. Since the project was actually imported, I assume there was something wrong with switching to the project page of the imported one. The upcoming release will provide more information when errors happen. It will help us locate the error.

It is a good idea to have an option to replace the existing project instead of creating a copy. Our team will discuss the implementation of this feature. Thanks for your valuable input!

**Comment by J535D165** [comment]
Closing this issue because no other users report this issue. Nevertheless, if someone experiences this issue, please let us know. Hopefully, the improved error messages in ASReview can help to debug this.
