### ISSUE TITLE
Stop simulation mode when all relevant documents are found

### ISSUE THREAD

**Issue by govertv** [asreview/asreview#598]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Simulation runs can take quite long for models with high computation times. The current default behavior is to stop the simulation when every single document has been labelled. However, after all relevant documents have been found, there is no reason to continue the simulation for most of the metrics currently used. A lot of computation time can be saved by stopping the simulation when all relevant documents are found.

![first_long_simulation](https://user-images.githubusercontent.com/42623130/117465718-42555600-af52-11eb-8602-1f9b490e9899.png)

**Describe the solution you'd like**
Add a CLI option that allows stopping the simulation when all relevant documents are found. This could probably be a default setting, though I'm sure there are some cases where it is useful to finish the full simulation run.

**Describe alternatives you've considered**
An alternative solution could be printing a message in the terminal when all relevant documents have been found. The user can then choose to stop the run by issuing a keyboard interrupt.

**Teachability, Documentation, Adoption, Migration Strategy**
Adding it to the current documentation about the CLI should be sufficient.

**Comment by govertv** [comment]
Integrating it with n_queries sounds fine to me. Implementing it myself sounds like a nice thing to try. One more thing to consider is that the output of the recall plot should probably look the same as when the run is completed fully.  I think this could be done in two different ways: either in the package that handles the visualisations, or when creating the statefile. I don't know which of these is the preferred solution.

**Comment by PeterLombaers** [comment]
Sounds like a smart idea to me! You'd save on some computing time, but you would lose the order in which the records are presented and the probabilities/ranking of the model for the last records. Since that ranking should be pretty stable after all relevant records have been labelled, you don't lose out on a lot I would think. At the very least it's a nice option to have.

The implementation should be the main asreview part, because that's where the simulations run, not in visualizations. I'm not completely sure where it should be. In the main reviewing loop for the simulation mode there should be some check if all relevant records have been labelled and then the reviewing loop stops?

**Comment by J535D165** [comment]
I think we should do two things:

1. Update ASReview and extend `n_queries` with `min` or `auto`. 
2. Update ASReview-visualization such that it can complete the recall curve. 

The latter one requires some interesting challenges I guess. For example, you need to check whether the simulation was not aborted because of anything else. Might be interesting to have this check in the new state file API @PeterLombaers (something like `StateFile.is_simulation_complete`). 

The relevant code for the first todo (afaik): 

https://github.com/asreview/asreview/blob/a296205f7fe1f2e4a09e1856bd5be01438d9223a/asreview/review/base.py#L242-L265

https://github.com/asreview/asreview/blob/a296205f7fe1f2e4a09e1856bd5be01438d9223a/asreview/settings.py#L26-L42

https://github.com/asreview/asreview/blob/a296205f7fe1f2e4a09e1856bd5be01438d9223a/asreview/entry_points/simulate.py#L172-L179

This will result in a backward incompatibility of state files using this value. However, it might be acceptable, isn't it?

@govertv I will assign you to this issue.
