### ISSUE TITLE
RIS file fails to import due to "Cannot find proper encoding for data file"

### ISSUE THREAD

**Issue by behrica** [asreview/asreview#602]
**Describe the bug**
I have a certain RIS file (with Greek characters) which fails to import

**To Reproduce**
use attached file and try to import.

**Screenshots**

**Version information**
 - OS: win
 - ASReview version. latest Docker,  0.1.7

**Additional context**

Stack trace:

```
WARNING:root:Expected start tag in line 0:
 ï»¿%0 Journal Article
WARNING:root:Expected start tag in line 0:
 %0 Journal Article
WARNING:root:Expected start tag in line 0:
 %0 Journal Article
ERROR:asreview.webapp.start_flask:Exception on /api/project/test/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/asreview/webapp/api.py", line 409, in api_upload_data_to_project
    add_dataset_to_project(project_id, filename)
  File "/usr/local/lib/python3.6/site-packages/asreview/webapp/utils/project.py", line 189, in add_dataset_to_project
    as_data = read_data(project_id)
  File "/usr/local/lib/python3.6/site-packages/asreview/webapp/utils/io.py", line 115, in read_data
    data_obj = ASReviewData.from_file(fp_data)
  File "/usr/local/lib/python3.6/site-packages/asreview/data/base.py", line 226, in from_file
    df, column_spec = read_fn(fp)
  File "/usr/local/lib/python3.6/site-packages/asreview/io/ris_reader.py", line 72, in read_ris
    raise ValueError("Cannot find proper encoding for data file.")
ValueError: Cannot find proper encoding for data file.
ERROR:root:Cannot find proper encoding for data file.
```

**Comment by behrica** [comment]
[ris.zip](https://github.com/asreview/asreview/files/6465508/ris.zip)

**Comment by ottomattas** [comment]
Thanks for the report, @behrica!

We are using [rispy](https://pypi.org/project/rispy/) to do the heavy lifting for ASReview and parse the RIS files. Among other features, it comes with encoding handling. Right now, it seems to be limited to UTF-8 and ISO-8859-1 so the Cyrillic characters are not recognised.

Just to bring the topic forward, I have opened [an issue](https://github.com/MrTango/rispy/issues/38) with the developers of [rispy](https://pypi.org/project/rispy/). If possible, let's move our discussions there to keep it all close to the source and in one place!

**Comment by ottomattas** [comment]
Follow this issue at the official repository for rispy:
https://github.com/MrTango/rispy/issues/38

**Comment by ottomattas** [comment]
It turns out there is a possibility that the file fails to open in ASReview due to formatting as [pointed out by rispy developers](https://github.com/MrTango/rispy/issues/38#issuecomment-843329956) and not encoding. In short, the file should have an entry which starts with a proper start tag **TY** (and end with **ER**).

@behrica, could you maybe see if adjusting your RIS file's formatting allows you to open it in ASReview? We have some generic RIS files also available in our repo so you can see what differs between your and [the generic file](https://github.com/asreview/asreview/blob/master/tests/demo_data/generic.ris).

On a side note - I am now wondering where this problematic file originates from? (e.g Is it from a website or an export from a relevant software we might want to support in the future, etc?)

**Comment by J535D165** [comment]
Actually, this error message is confusing because it is raised when the parser fails. 

Look at this part of the code:

https://github.com/asreview/asreview/blob/ac7e72d555851c417aacdb6f20551f4448c99c20/asreview/io/ris_reader.py#L58-L72

So when IO error is raised (and there is no encoding error), the error message will be EncodingError... PR #603 makes changes in this part of the code, but doesn't resolve this. Maybe first finish #603 and then implement an informative error. @ottomattas what do you think?

**Comment by behrica** [comment]
> 
> On a side note - I am now wondering where this problematic file originates from? (e.g Is it from a website or an export from a relevant software we might want to support in the future, etc?)

It is exported from Endnote.

**Comment by behrica** [comment]
But indeed, the file does not look like a RIS file at all.
It is a "tagged" format, but the tags are not "RIS" tags, as described here:
https://en.wikipedia.org/wiki/RIS_(file_format)

**Comment by behrica** [comment]
I am pretty sure I "exported as RIS", but this is somehow not true.
I found the "tags" described here: https://en.wikipedia.org/wiki/EndNote#Tags_and_fields

There is probably confusion on my side, what "export as text" / RIS in Endnote is supposed to do.
