### ISSUE TITLE
A predefined filter for the title or abstract would be useful.

### ISSUE THREAD

**Issue by Mohammadkar** [asreview/asreview#686]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I tested the ASReview to screen around 1000 citations. The system works based on my selection of studies. Choosing relevant and irrelevant would help the system generate an algorithm to bring up the most relevant titles and abstracts and accelerate screening.  The issue is that some of the titles are relevant in nature but because they are protocols, I have to select the option "irrelevant". This is while the title is quite relevant and should be used for generating a more accurate algorithm. If I cannot filter out the protocols beforehand, I may not be able to teach the system efficiently to pull up the most relevant articles in a shorter time. Or I have to be more cautious and screen most of the citations to not missing any relevant article. 

**Describe the solution you'd like**
The solution could be adding an option for filtering out the citations having titles with a specific word such as "protocol" before starting the study selection. If I have to exclude protocols or any other keywords, even if the research topic is quite relevant, I should be able to filter out all the citations for that keyword and exclude them from the pool before starting the screening. In this way, there are no records with the keyword in the titles that I have to exclude while the whole topic is relevant (other words in the title should be used for enhancing the algorithm). I hope this is understandable. 

**Describe alternatives you've considered**
I am not sure if you believe the system would recognize the keyword after a few exclusions, it may solve the issue; however, I do not think this is the solution because when I say "irrelevant," the system would put all the words from the title in the "irrelevant keyword list" which would be misleading for the algorithm. Is not that right? I do not think about any other alternative solution. Other researchers may help in this regard. 

**Teachability, Documentation, Adoption, Migration Strategy**
The user can enter the keyword for pre-filtering at the beginning and ask the system to filter out all the abstracts with specific keywords and have the information, including the total number of citations that filtered out for that keyword.

**Comment by Rensvandeschoot** [comment]
Dear @Mohammadkar,

Thank you for your interest in our open source software and great to hear you are succesfull in finding relevant papers! 

I can understand your request for adding a filter to the software. However, other software is much better in pre-processing data and we would like to spend our resources on improving the algoritms even further because that is where we can make the difference. 

Feel free to open an item on our [discussion board ](https://github.com/asreview/asreview/discussions) on different ways for dealing with your situation (eg., you can already filter out protocols in your search query so that these do not end-up in the dataset at all) and I will invite some information specialists to join the discussion.
