### ISSUE TITLE
Setup of a large dataset

### ISSUE THREAD

**Issue by tlaso** [asreview/asreview#742]
**Describe the bug**

I can't manage to "Finish setup" of a large dataset. The first training never ends. I think it has something to do with the fact that the file is almost 2GB, with >1M papers.

*What happened? And what did you expect to happen?*

When I click FINISH in the FINISH SETUP screen, it stalls:

![image](https://user-images.githubusercontent.com/90268625/133986913-a159331d-fb86-4c90-aa7f-2c354ac10cbb.png)

Stays like this forever:

![image](https://user-images.githubusercontent.com/90268625/133986738-6c2b9a6b-03bd-418a-9d80-a848f875e4b5.png)

**To Reproduce**
Steps to reproduce the problem:

1. Upload a large file
2. Run the first training

**Version information**
 - OS: Debian
 - ASReview version 0.17.1

**Additional context**

The process of using such a large file has been problematic. To upload it, I had to send the file directly to the server and then run a small python line to add the project with the dataset manually:

```python
# use the utils functions
import asreview.webapp.utils.project as proj
# assign the necessary variables
info = ['proj_id', ...]; data = 'loc_to_data'
# add the project to asreview
proj.init_project(*info)
# manually add the dataset
proj.add_dataset_to_project(info[0], data)
```

Before using the current setup, the VM was too weak and would give me a "low memory" error, but now with a stronger VM it simply stops training and doesn't even warn me that it had an error. 

By running "htop", I see that the CPU activity stops after about 30 seconds.

**Comment by ottomattas** [comment]
Hi @tlaso , thanks for reporting the issue. Is it possible for you to make the dataset available for us so that we can recreate and verify the issue? (It would really help us help you if we see this issue directly on our side as well.)

**Comment by tlaso** [comment]
Hi, @ottomattas. Thank you for your attention. [Here](https://storage.googleapis.com/asreview/asreview.csv) it goes!

**Comment by ottomattas** [comment]
Thanks for the data. First thing I see is that you are trying to use a .xls file format which we do not support (check here: https://asreview.readthedocs.io/en/latest/intro/datasets.html#data-format).

Can you prepare your data in one of the supported formats and try again?
(Let's do this first to exclude any problems that might be coming from the formatting.)

**Comment by ottomattas** [comment]
Just some more details around this issue - I just converted the .xls file to a .csv file without managing any aspects of it. Just to see what happens and these are the things I can see right away:
* There are 999999 records instead of 1147412 as seen on the initial screenshot
* The project setup finishes after 6'52'' of training (on my MacBook Pro (13-inch, M1, 2020)), using the same learning model as as seen on the initial screenshot
* The backend application does not throw any errors during the process

<img width="1440" alt="Screenshot 2021-09-20 at 15 01 27" src="https://user-images.githubusercontent.com/15941300/133998772-ed87fb1c-0806-40cf-b8d6-4046749cff7c.png">

**Comment by tlaso** [comment]
> Thanks for the data. First thing I see is that you are trying to use a .xls file format which we do not support (check here: https://asreview.readthedocs.io/en/latest/intro/datasets.html#data-format).
> 
> Can you prepare your data in one of the supported formats and try again?
> (Let's do this first to exclude any problems that might be coming from the formatting.)

I must have sent the wrong file. Sorry. I have doubled checked and reuploaded it.

> * The project setup finishes after 6'52'' of training (on my MacBook Pro (13-inch, M1, 2020)), using the same learning model as seen on the initial screenshot

This must be it. My VM is still too weak. You didn't change any parameters/configurations, right?

**Comment by ottomattas** [comment]
> I must have sent the wrong file. Sorry. I have doubled checked and reuploaded it.
> 
No worries, these thing happen. Anyway, I recommend to move over to .xlsx if Excel is necessary. The older format .xls is not supported for many reasons. First and foremost, [Microsoft has stopped support for Office 2003 since 2014](https://support.microsoft.com/en-us/office/support-has-ended-for-office-2003-c5118100-b738-4163-b7c1-b9c4fe5b6b90), and .xls was the default for Excel 2003.

For a quick remedy, you can turn your .xls files to .csv and use those with ASReview. Also, this should save some space on the drive.
 
> This must be it. My VM is still too weak. You didn't change any parameters/configurations, right?

This might be the case so giving it time would solve the issue for now. I did not change any parameters or settings. I just ran the workflow on a clean install with some additional logging turned on for debugging purposes.

For the future - I would also consider limiting the scope of the search (and therefore the number of records). Of course, ASReview can technically handle these kind of heavy workloads but is it actually the best course of action for the researcher? I mean, having random records is very relevant. But how many is too many?

**Comment by ottomattas** [comment]
@tlaso , can you check again with the new dataset (with a supported format) and verify it worked out nicely for you?

**Comment by tlaso** [comment]
You are right about the size of the sample. We will, for sure, learn that lesson the hard way.

I had to increase to RAM up to 50gb so that it would finish the initial training. Memory was still the bottleneck. It touched the 48GB of usage at the apex. The csv file that I shared the second time, with the 1.1M papers, worked just fine.

The problem lied on my side. Thank you for your help.

**Comment by ottomattas** [comment]
Thanks for the confirmation and feedback.As for the memory consumption - I was happily running the workload on a laptop with 16GB available memory. The process did not exhaust the full capacity of my memory, though and I was able to keep running my other applications at the same time as per usual. So if you have a bigger dataset, you can do it also under lower technical specification while having a little more patience. No need to spend a lot of money on just the setup.

I'm glad it worked out. Always happy to collaborate and see a problem get solved!
I hope you can get some amazing and relevant results. Happy hunting! :)
