### ISSUE TITLE
batch_size argument in Sentence Transformer seems not to be taken into account

### ISSUE THREAD

**Issue by merdivane** [asreview/asreview#870]
Hi, we are trying to use Bert as a feature extractor. It seems batch size is not taken into account. If we have 10 documents we can see 10 HTTP Requests to api/.../init_ready. If we increase batch size we don't see any difference in performance and get the same number of HTTP requests.  Could you please let us know how to increase the performance with increasing batch_size ? Thank you for your time in advance.
![Screenshot 2021-12-02 at 17 21 08](https://user-images.githubusercontent.com/70752296/144462370-1491d0be-cc35-42f7-9320-a64d257f9f9b.png)

**Comment by PeterLombaers** [comment]
Hello! The request to init_ready means that the software is checking if the feature matrix is created and the model is trained, so that it can start the review process. In does not mean that a batch is being processed at every request. 
If I'm correct the batch_size should be handled automatically by the sentence_transformers library, so it should be optimized already. In any case, you can't adjust the batch_size in ASReview right now. It's just a matter of waiting for the feature extraction and model training to be finished.
Does this help?

**Comment by Rensvandeschoot** [comment]
It seems this question has been answered by @PeterLombaers.

 @merdivane feel free to re-open the issue if you have further questions.
