### ISSUE TITLE
unable to upload .txt file

### ISSUE THREAD

**Issue by yassenenzo** [asreview/asreview#871]
**Describe the bug**
When I tried to upload a .txt file containing all my references, ASReview could not find proper encoding for the data file. I don't know how to solve this.

**To Reproduce**
Go to your project. Go to finish setup. Put .txt data file in the box. Click on upload. 

**Version information**
 - OS: [Windows]
 - ASReview version [e.g. 0.18]

**Comment by SagevdBrand** [comment]
Hi there @yassenenzo!

Thanks for reporting your bug!
Could you do either one of the following?
1. Tell us how you created the .txt file
2. Send a screenshot of the content of your .txt file (can be a just of record)
3. Send your .txt file to asreview@uu.nl

Thank you!

**Comment by yassenenzo** [comment]
![Knipsel](https://user-images.githubusercontent.com/95024817/145010942-fbead021-88ed-43cc-b85c-588d8b74a6ba.PNG)

Hi,
This is the screenshot of my .txt file. I created it in pubmed. I hope to hear from you soon.
Thank you in advance!

**Comment by SagevdBrand** [comment]
Hi @yassenenzo ,

I think I see what the problem is, the .txt file PUBMED creates is not in RIS format, making it unreadable for ASReview LAB unfortunately. 

However, there is a work around:

1. Export your search results as an `.nbib` file. To download the `.nbib` file you can follow these instructions: https://pubmed.ncbi.nlm.nih.gov/help/#citation-management-software.
2. Import this `.nbib` file to your reference manager (EndNote for example, which is also very useful for deduplicating search results and retrieving missing abstracts). 
3. Export the library from your reference manager in RIS format (For EndNote see these instructions for example: https://libguides.jcu.edu.au/c.php?g=829543&p=6602335)
4. Upload to the RIS formatted file to ASReview. 

Let me know if this works for you!

**Comment by yassenenzo** [comment]
Hi!
It worked, thank you! I used Zotero instead of EndNote and this worked as well.
Thanks again!

**Comment by SagevdBrand** [comment]
Yay, glad to hear it worked out! Good luck with screening!
