### ISSUE TITLE
Fail to edit project info after upgrading an old project

### ISSUE THREAD

**Issue by terrymyc** [asreview/asreview#952]
The old project does not have a `mode`. When updating the project basic information, `update_project_info` returns `ValueError: Project mode 'undefined' not found.` It prevents updating any information.

**Comment by J535D165** [comment]
This sounds like something that needs to be added to the converter, isn't it?

Can you indicate where you are calling this function and what arguments you have? Because this should only fail if you are resending "undefined" to the function. 

See 

https://github.com/asreview/asreview/blob/902cd4de6b71d52afb921f36d62a946f01c3e351/asreview/webapp/utils/project.py#L187-L190

I'm wondering when you try to update the mode (this shouldn't be an option, isn't it?). 

However is still a good idea to update the converter, because projects without mode are hard to open. Project mode should always be oracle. Even if it's an `explore` project.

**Comment by J535D165** [comment]
Something like 

```python
project_info.get('mode', 'oracle') 
```

here

https://github.com/asreview/asreview/blob/902cd4de6b71d52afb921f36d62a946f01c3e351/asreview/state/sql_converter.py#L140-L182

Ping @PeterLombaers

**Comment by terrymyc** [comment]
I agree to add it to the converter. Currently, an old project does not have a mode after it is upgraded. However, updating project info requires passing a value for `mode`. That is why `undefined` is passed when other properties like authors are edited.

**Comment by terrymyc** [comment]
This issue is temporarily fixed by removing `mode` from the `PUT` API for updating project info. However, another use case is affected. When creating a new project in the first step, the `POST` API will be called once the title is filled and the text field loses focus, which means a project is initiated. It is not possible to change the mode after this action.

Currently, in the frontend, the mode select is disabled after you move on to the second step. This is now affected by not allowing any change after the title text field loses focus (the project has been initiated).

A specific question is whether we allow the change of mode during the setup (perhaps not limited to step 1). If we allow, we still need the `mode` option in the `PUT` API.

A fundamental fix in the converter is necessary.
